---
- name: handler demo
  hosts: localhost
  connection: local
  tasks:
    - name: Uptime
      ansible.builtin.command: "uptime"
      notify: message
  handlers:
    - name: message 1
      ansible.builtin.debug:
        msg: message 1
      listen: message
    - name: message 2
      ansible.builtin.debug:
        msg: message 2
      listen: message
